# Generated by Django 4.0.1 on 2022-01-29 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный пользователь'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='администратор сайта'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='ник пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_sex',
            field=models.CharField(max_length=1, verbose_name='пол пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_surname',
            field=models.CharField(max_length=50, verbose_name='фамилия пользователя'),
        ),
    ]
