# Generated by Django 4.0.1 on 2022-01-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='о себе.'),
        ),
    ]
