# Generated by Django 4.0.1 on 2022-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_avatar',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='аватар пользователя'),
        ),
    ]
