# Generated by Django 4.0.1 on 2022-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_groups_alter_newuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_nickname',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_avatar',
            field=models.ImageField(upload_to='', verbose_name='аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не выбран'), (2, 'Женский'), (3, 'Мужской')], default=1),
        ),
    ]
