# Generated by Django 4.0.1 on 2022-01-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_options_remove_newuser_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_sex',
            field=models.PositiveSmallIntegerField(choices=[('-', 'Не выбран'), ('w', 'Женский'), ('m', 'Мужской')], default='-'),
        ),
    ]
