# Generated by Django 4.0.1 on 2022-01-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_newuser_avatar_alter_newuser_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_avatar',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='аватар '),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='имя '),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_sex',
            field=models.CharField(choices=[('-', 'Не выбран'), ('w', 'Женский'), ('m', 'Мужской')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
